"""
Clean up test data generated by pytest runs.
Deletes all users except admin, testuser, testuser2,
and all genealogies/members/relations created by other users.
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
import mysql.connector
from config import DATABASE_CONFIG

KEEP_USERS = ('admin', 'testuser', 'testuser2')


def clean(conn):
    cursor = conn.cursor(dictionary=True)

    print("Starting cleanup...")

    # Get users to delete
    cursor.execute("""
        SELECT user_id, username FROM users
        WHERE username NOT IN (%s, %s, %s)
    """, KEEP_USERS)
    users = cursor.fetchall()
    if not users:
        print("No users to delete.")
        return
    user_ids = [u['user_id'] for u in users]
    placeholders = ','.join(['%s'] * len(user_ids))

    # Get genealogies to delete
    cursor.execute(f"""
        SELECT genealogy_id, name FROM genealogies
        WHERE created_by IN ({placeholders})
    """, user_ids)
    genealogies = cursor.fetchall()

    if genealogies:
        g_ids = [g['genealogy_id'] for g in genealogies]
        g_placeholders = ','.join(['%s'] * len(g_ids))

        # 1. Delete marriages (via members in those genealogies)
        cursor.execute(f"""
            DELETE mar FROM marriages mar
            JOIN members m ON mar.member_id1 = m.member_id OR mar.member_id2 = m.member_id
            WHERE m.genealogy_id IN ({g_placeholders})
        """, g_ids)
        print(f"  Deleted {cursor.rowcount} marriages")

        # 2. Delete family_links (via members in those genealogies)
        cursor.execute(f"""
            DELETE fl FROM family_links fl
            JOIN members m ON fl.child_id = m.member_id
            WHERE m.genealogy_id IN ({g_placeholders})
        """, g_ids)
        print(f"  Deleted {cursor.rowcount} family_links")

        # 3. Delete members
        cursor.execute(f"""
            DELETE FROM members
            WHERE genealogy_id IN ({g_placeholders})
        """, g_ids)
        print(f"  Deleted {cursor.rowcount} members")

        # 4. Delete collaborations
        cursor.execute(f"""
            DELETE FROM collaborations
            WHERE genealogy_id IN ({g_placeholders})
        """, g_ids)
        print(f"  Deleted {cursor.rowcount} collaborations")

        # 5. Delete genealogies
        cursor.execute(f"""
            DELETE FROM genealogies
            WHERE genealogy_id IN ({g_placeholders})
        """, g_ids)
        print(f"  Deleted {cursor.rowcount} genealogies")
    else:
        print("  No genealogies to delete.")

    # 6. Delete collaborations that might reference deleted users directly
    cursor.execute(f"""
        DELETE FROM collaborations
        WHERE user_id IN ({placeholders})
    """, user_ids)
    print(f"  Deleted {cursor.rowcount} remaining collaborations (by user)")

    # 7. Delete users
    cursor.execute(f"""
        DELETE FROM users
        WHERE user_id IN ({placeholders})
    """, user_ids)
    print(f"  Deleted {cursor.rowcount} users")

    conn.commit()
    print("Cleanup completed successfully!")


if __name__ == '__main__':
    conn = mysql.connector.connect(**DATABASE_CONFIG)
    try:
        clean(conn)
    finally:
        conn.close()