#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Import CSV data into MySQL using LOAD DATA LOCAL INFILE.

Imports the CSV files generated by generate_mock_data.py:
  1. genealogies.csv  -> genealogies table
  2. members.csv      -> members table
  3. family_links.csv -> family_links table
  4. marriages.csv    -> marriages table

Prerequisites:
  - MySQL server running
  - Database genealogy_db exists (run schema.sql first)
  - A user with user_id=1 exists in users table (for created_by FK)
  - CSV files in data/ directory (run generate_mock_data.py first)

Usage:
  python scripts/import_csv.py [--truncate]
  
  --truncate  : Clear existing data before import (optional)
"""

import argparse
import os
import sys
import time

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import mysql.connector
from config import DATABASE_CONFIG

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data")


def get_connection():
    """Create MySQL connection with local_infile enabled."""
    config = DATABASE_CONFIG.copy()
    config["allow_local_infile"] = True
    return mysql.connector.connect(**config)


def ensure_user_exists(conn):
    """Ensure user_id=1 exists for the created_by foreign key."""
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM users WHERE user_id = 1")
    if cursor.fetchone()[0] == 0:
        import hashlib
        pw_hash = hashlib.sha256("admin123".encode()).hexdigest()
        cursor.execute(
            "INSERT INTO users (user_id, username, password_hash, email) "
            "VALUES (1, 'admin', %s, 'admin@genecloud.local')",
            (pw_hash,)
        )
        conn.commit()
        print("  Created default admin user (user_id=1)")
    else:
        print("  Admin user already exists")
    cursor.close()


def truncate_tables(conn):
    """Truncate all data tables (respecting FK order)."""
    cursor = conn.cursor()
    # Disable FK checks temporarily
    cursor.execute("SET FOREIGN_KEY_CHECKS = 0")
    tables = ["family_links", "marriages", "members", "genealogies"]
    for table in tables:
        cursor.execute(f"TRUNCATE TABLE {table}")
        print(f"  Truncated {table}")
    cursor.execute("SET FOREIGN_KEY_CHECKS = 1")
    conn.commit()
    cursor.close()


def load_csv_file(cursor, filepath, table, columns, skip_rows=1):
    """Load a CSV file into a MySQL table using LOAD DATA LOCAL INFILE."""
    # Use forward slashes for MySQL path compatibility
    mysql_path = filepath.replace("\\", "/")

    cols_str = ", ".join(columns)

    sql = (
        f"LOAD DATA LOCAL INFILE '{mysql_path}' "
        f"INTO TABLE {table} "
        f"CHARACTER SET utf8mb4 "
        f"FIELDS TERMINATED BY ',' "
        f"OPTIONALLY ENCLOSED BY '\"' "
        f"LINES TERMINATED BY '\\n' "
        f"IGNORE {skip_rows} LINES "
        f"({cols_str})"
    )

    cursor.execute(sql)
    return cursor.rowcount


def import_genealogies(conn):
    """Import genealogies.csv."""
    path = os.path.join(DATA_DIR, "genealogies.csv")
    if not os.path.exists(path):
        print(f"  SKIP: {path} not found")
        return 0

    cursor = conn.cursor()
    count = load_csv_file(cursor, path, "genealogies",
                          ["genealogy_id", "name", "surname", "created_by"])
    conn.commit()
    cursor.close()
    print(f"  Imported {count} rows into genealogies")
    return count


def import_members(conn):
    """Import members.csv."""
    path = os.path.join(DATA_DIR, "members.csv")
    if not os.path.exists(path):
        print(f"  SKIP: {path} not found")
        return 0

    cursor = conn.cursor()
    count = load_csv_file(cursor, path, "members",
                          ["member_id", "genealogy_id", "name", "gender",
                           "birth_year", "death_year", "bio"])
    conn.commit()
    cursor.close()
    print(f"  Imported {count} rows into members")
    return count


def import_family_links(conn):
    """Import family_links.csv."""
    path = os.path.join(DATA_DIR, "family_links.csv")
    if not os.path.exists(path):
        print(f"  SKIP: {path} not found")
        return 0

    cursor = conn.cursor()
    count = load_csv_file(cursor, path, "family_links",
                          ["child_id", "parent_id", "relation_type"])
    conn.commit()
    cursor.close()
    print(f"  Imported {count} rows into family_links")
    return count


def import_marriages(conn):
    """Import marriages.csv."""
    path = os.path.join(DATA_DIR, "marriages.csv")
    if not os.path.exists(path):
        print(f"  SKIP: {path} not found")
        return 0

    cursor = conn.cursor()
    count = load_csv_file(cursor, path, "marriages",
                          ["member_id1", "member_id2",
                           "marriage_year", "divorce_year"])
    conn.commit()
    cursor.close()
    print(f"  Imported {count} rows into marriages")
    return count


def verify_counts(conn):
    """Print row counts for each table."""
    cursor = conn.cursor()
    tables = ["genealogies", "members", "family_links", "marriages"]
    print("\n--- Table Row Counts ---")
    for table in tables:
        cursor.execute(f"SELECT COUNT(*) FROM {table}")
        count = cursor.fetchone()[0]
        print(f"  {table:20s}: {count:,}")
    cursor.close()


def main():
    parser = argparse.ArgumentParser(description="Import CSV data into MySQL")
    parser.add_argument("--truncate", action="store_true",
                        help="Clear existing data before import")
    args = parser.parse_args()

    print("=" * 60)
    print("CSV Import Tool for Genecloud")
    print("=" * 60)

    # Check data directory
    if not os.path.isdir(DATA_DIR):
        print(f"\nERROR: Data directory not found: {DATA_DIR}")
        print("Run 'python scripts/generate_mock_data.py' first.")
        sys.exit(1)

    # Connect
    print("\nConnecting to MySQL...")
    try:
        conn = get_connection()
    except mysql.connector.Error as e:
        print(f"ERROR: Cannot connect to MySQL: {e}")
        sys.exit(1)

    try:
        # Enable local_infile on server side
        cursor = conn.cursor()
        cursor.execute("SET GLOBAL local_infile = 1")
        cursor.close()

        # Ensure admin user exists
        print("\nChecking prerequisites...")
        ensure_user_exists(conn)

        # Truncate if requested
        if args.truncate:
            print("\nTruncating tables...")
            truncate_tables(conn)

        # Import in FK order
        print("\nImporting data...")
        t0 = time.time()

        print("\n[1/4] Importing genealogies...")
        import_genealogies(conn)

        print("[2/4] Importing members...")
        import_members(conn)

        print("[3/4] Importing family_links...")
        import_family_links(conn)

        print("[4/4] Importing marriages...")
        import_marriages(conn)

        elapsed = time.time() - t0
        print(f"\nImport completed in {elapsed:.1f}s")

        # Verify
        verify_counts(conn)

    finally:
        conn.close()
        print("\nConnection closed.")


if __name__ == "__main__":
    main()